name: Build Wordpress static Docker Image

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        run: docker login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: Build Wordpress Docker image
        run: docker build --pull --tag wordpress_static ./
      - name: Tag and push image
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE_VERSION=$(docker run --entrypoint /bin/sh wordpress_static -c 'grep "wp_version = " wp-includes/version.php | grep -Eo "[0-9.]+"')
          docker tag wordpress_static "ghcr.io/patrick246/wordpress:$IMAGE_VERSION"
          docker push "ghcr.io/patrick246/wordpress:$IMAGE_VERSION"